### PR TITLE
Added check output test

### PR DESCRIPTION
**Pull request by MarcoCouto**

### CODE REVIEW

**Review by fntneves — CHANGES_REQUESTED** [review]
In general, I like it. However, I am not convinced that assertEqual returns true if Team B appears before Team C. 🤔  Can you check this out?

Recalling our last conversation, maybe testing the output file would be stronger than this test, since the output dict may depend of the chosen solver.

**Comment by MarcoCouto** [comment]
@fntneves, the module returns a string, correct?
If so, the test can parse the output, and check if each team has assigned the correct task(s). What do you think?

Btw, maybe a better approach would be to make the module return a list of dictionaries. It's easier to interpret, and can be easly converted to JSON, for instance.

**Comment by fntneves** [comment]
@MarcoCouto No, the distribute method returns a dict. This test works, but is should be able to tolerate different orders. I do not know if equals return false if the order of keys is different. I assume it is smart enough to keep returning true, since dicts do not have order. 🤔 

Regarding to the output model file, I am creating a pull request to let you validate it.

**Comment by MarcoCouto** [comment]
@fntneves, if it returns a dict then I just need to check if the keys have the corresponding values, don't you think? This, of course, considering that the test will return false if the order changes.

Regarding the other issue, I'm waiting :)

**Comment by fntneves** [comment]
@MarcoCouto I am done with the PR. You can check it ;)

Yes, the problem is: What does assertEqual return if the order of tasks assigned to User 2 is displayed in different order?

Something like this:

```python
## Is it True ?

assertEqual({ 'user2': ['a', 'b'] }, { 'user2': ['b, 'a'] })
```

In theory, it should return true, because both are similar. However, how strict is assertEqual() ? Maybe you should sort lists before assertEqual().

It recalls the original problem: Is this test relevant to test the model ? Once model output is validated, this test only cares about the format of the data returned by the distribute method.

**Comment by MarcoCouto** [comment]
@fntneves, I will deal with the Pull Request ASAP.

I understood what you said, and I'm adapting the test accordingly ASAP.

**Comment by MarcoCouto** [comment]
@fntneves, I checked the `assertEqual` for the last test returns `True ` even if the order of the keys in the dict is mixed.
I guess you can accept the PR ;)

**Comment by fntneves** [comment]
screen shot 2017-03-29 at 23 32 09
@MarcoCouto I've tested it, also, and I am not able to get the same output. Please ensure that you are running against Python 3.4+

For me, the statement I've mentioned before returns False 🤔

**Comment by MarcoCouto** [comment]
Really? The test failed? Strange...
I will check it properly ASAP, a commit my changes to this branch.

**Review by fntneves — CHANGES_REQUESTED** [review]
Seems good!
Please, just a detail. Change variable names from camelCase to snake_case, and we're done !

**Review by fntneves — APPROVED** [review]

**Comment by fntneves** [comment]
Please, *squash and merge* and remove the commit message related to var names

**Pull request merged**
