### PR TITLE
Add test for model output

### PR DESCRIPTION
**Pull request by fntneves**
This PR proposes to add a test to verify if the output model file matches the expected model.

It validates the generation of the model.

**resources/model.lp** is the file that contains the expected model.

### CODE REVIEW

**Review by MarcoCouto — COMMENTED** [review]
Looks ok to me!
Just a suggestion: shouldn't the `resources` folder be called `test-resources`? Because it only exists for test purposes. This can lead to some misunderstandings.

**Comment by fntneves** [comment]
@MarcoCouto The resources folder is actually inside the tests folder. Please take a look at the files of this PR.

**Comment by MarcoCouto** [comment]
@fntneves, yes I noticed the `resources` folder was inside the `test` folder.
I still thought that changing the name was appropriate, but maybe you're right.

**Review by MarcoCouto — APPROVED** [review]
I am accepting this PR ;)

**Pull request merged**
